site_name: Diesel-Electric
site_url: https://sitename.example

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/favicon/favicon.png
  features:
    - navigation.footer
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
extra_css:
  - assets/css/extra.css
validation:
  nav:
    omitted_files: ignore

nav:
  - Home: index.md
  - Categories:
      - "Hull and Compartments": "categories/hull-and-compartments/index.md"
      - "US WW2 Subs in General": "categories/us-ww2-subs-in-general/index.md"

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde