site_name: Diesel-Electric Submarine FAQs
site_description: An open-source knowledge base on U.S. WWII diesel-electric submarines
site_author: Dwight Naset and Irving Greisman
site_url: https://diesel-subs.github.io/diesel-subs/

repo_name: diesel-subs/diesel-subs
repo_url: https://github.com/diesel-subs/diesel-subs
edit_uri: edit/main/docs/

extra_css:
  - assets/css/extra.css
extra_javascript:
  - assets/js/active-branch.js
  - assets/js/feedback-link.js
  - assets/js/open-summary-tab.js

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true

theme:
  name: material
  language: en
  custom_dir: overrides
  logo: assets/images/logo.png
  favicon: assets/favicon/favicon.ico
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  features:
    - navigation.footer
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

validation:
  nav:
    omitted_files: ignore

nav:
  - Home: index.md
  - Hull and Compartments: "categories/Hull and Compartments/index.md"

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
