site_name: Diesel-Electric Submarine FAQs
site_url: https://igreisman.github.io/Diesel-Electric-Submarine-FAQs/


extra_css:
  - assets/css/extra.css
extra_javascript:
  - assets/js/active-branch.js

plugins:
  - search


theme:
  name: material
  custom_dir: overrides
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/images/logo.png
  favicon: assets/favicon/favicon.ico
  features:
    - navigation.footer
    - content.tabs
    - content.tabs.link  # optional, allows deep linking to tabs
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

validation:
  nav:
    omitted_files: ignore

nav:
  - Home: index.md
  - Hull and Compartments: "categories/hull-and-compartments/index.md"
  - US WW2 Subs in General: "categories/us-ww2-subs-in-general/index.md"
  - Operating US Subs in WW2: "categories/operating-us-subs-in-ww2/index.md"
  - Life Aboard WW2 US Subs: "categories/life-aboard-ww2-us-subs/index.md"
  - Crews Aboard WW2 US Subs: "categories/crews-aboard-ww2-us-subs/index.md"
  - Attacks and Battles, Small and Large: "categories/attacks-and-battles-small-and-large/index.md"
  - Join us ...: "#"

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
